openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/notebook:
    get:
      summary: ''
      operationId: getApiV1Notebook
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: 1
                  error: false
                  notebooks:
                    -
                      id: 1
                      fio: 'Dr. Godfrey Howell'
                      name: 'Funk, Waters and Sawayn'
                      phone: 941-324-3259
                      email: leffler.ansley@example.net
                      birthday: 27/02/1994
                    -
                      id: 2
                      fio: 'Ms. Delpha Cronin'
                      name: 'Morar PLC'
                      phone: 1-606-364-9169
                      email: meda.upton@example.net
                      birthday: 04/03/2004
                    -
                      id: 3
                      fio: 'Ashtyn Crona'
                      name: 'Cole Ltd'
                      phone: 985.553.4099
                      email: aaron.nicolas@example.com
                      birthday: 26/11/2006
                    -
                      id: 4
                      fio: 'Idell Reichert'
                      name: Weber-Hamill
                      phone: '(725) 702-1469'
                      email: blick.dustin@example.org
                      birthday: 01/08/2006
                    -
                      id: 5
                      fio: 'Mr. Evans Nitzsche PhD'
                      name: 'Mann, Moore and Bernier'
                      phone: +1-954-405-5051
                      email: fisher.forrest@example.net
                      birthday: 14/02/2006
                    -
                      id: 6
                      fio: 'Ellen Corkery'
                      name: Botsford-Koepp
                      phone: +1.540.291.2039
                      email: khills@example.com
                      birthday: 15/09/1992
                    -
                      id: 7
                      fio: 'Mrs. Kelli Morar'
                      name: Jast-Johnston
                      phone: +1.657.234.6965
                      email: wiegand.regan@example.net
                      birthday: 18/04/1999
                    -
                      id: 8
                      fio: "Loma O'Connell"
                      name: 'Keeling Group'
                      phone: '+1 (386) 225-2709'
                      email: amari.douglas@example.org
                      birthday: 07/03/1999
                    -
                      id: 9
                      fio: 'Darion Braun'
                      name: Buckridge-Moen
                      phone: +1.680.410.9865
                      email: bergnaum.dejah@example.org
                      birthday: 23/02/2005
                    -
                      id: 10
                      fio: 'Miss Zita Abshire I'
                      name: Hettinger-Wunsch
                      phone: '+1 (240) 785-4726'
                      email: helmer83@example.com
                      birthday: 20/06/2006
                    -
                      id: 11
                      fio: 'Sapa Shirmadov'
                      name: Feature-Group
                      phone: '+79621665588'
                      email: sapa@gmail.com
                      birthday: 25-01-2000
                    -
                      id: 13
                      fio: 'Sapa Shirmadov'
                      name: Feature-Group
                      phone: '+79621665588'
                      email: sapa2@gmail.com
                      birthday: 25/01/2000
                properties:
                  status:
                    type: integer
                    example: 1
                  error:
                    type: boolean
                    example: false
                  notebooks:
                    type: array
                    example:
                      -
                        id: 1
                        fio: 'Dr. Godfrey Howell'
                        name: 'Funk, Waters and Sawayn'
                        phone: 941-324-3259
                        email: leffler.ansley@example.net
                        birthday: 27/02/1994
                      -
                        id: 2
                        fio: 'Ms. Delpha Cronin'
                        name: 'Morar PLC'
                        phone: 1-606-364-9169
                        email: meda.upton@example.net
                        birthday: 04/03/2004
                      -
                        id: 3
                        fio: 'Ashtyn Crona'
                        name: 'Cole Ltd'
                        phone: 985.553.4099
                        email: aaron.nicolas@example.com
                        birthday: 26/11/2006
                      -
                        id: 4
                        fio: 'Idell Reichert'
                        name: Weber-Hamill
                        phone: '(725) 702-1469'
                        email: blick.dustin@example.org
                        birthday: 01/08/2006
                      -
                        id: 5
                        fio: 'Mr. Evans Nitzsche PhD'
                        name: 'Mann, Moore and Bernier'
                        phone: +1-954-405-5051
                        email: fisher.forrest@example.net
                        birthday: 14/02/2006
                      -
                        id: 6
                        fio: 'Ellen Corkery'
                        name: Botsford-Koepp
                        phone: +1.540.291.2039
                        email: khills@example.com
                        birthday: 15/09/1992
                      -
                        id: 7
                        fio: 'Mrs. Kelli Morar'
                        name: Jast-Johnston
                        phone: +1.657.234.6965
                        email: wiegand.regan@example.net
                        birthday: 18/04/1999
                      -
                        id: 8
                        fio: "Loma O'Connell"
                        name: 'Keeling Group'
                        phone: '+1 (386) 225-2709'
                        email: amari.douglas@example.org
                        birthday: 07/03/1999
                      -
                        id: 9
                        fio: 'Darion Braun'
                        name: Buckridge-Moen
                        phone: +1.680.410.9865
                        email: bergnaum.dejah@example.org
                        birthday: 23/02/2005
                      -
                        id: 10
                        fio: 'Miss Zita Abshire I'
                        name: Hettinger-Wunsch
                        phone: '+1 (240) 785-4726'
                        email: helmer83@example.com
                        birthday: 20/06/2006
                      -
                        id: 11
                        fio: 'Sapa Shirmadov'
                        name: Feature-Group
                        phone: '+79621665588'
                        email: sapa@gmail.com
                        birthday: 25-01-2000
                      -
                        id: 13
                        fio: 'Sapa Shirmadov'
                        name: Feature-Group
                        phone: '+79621665588'
                        email: sapa2@gmail.com
                        birthday: 25/01/2000
                    items:
                      type: object
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiV1Notebook
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/notebook/{id}':
    get:
      summary: ''
      operationId: getApiV1NotebookId
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: 1
                  error: false
                  notebook:
                    -
                      id: 1
                      fio: 'Dr. Godfrey Howell'
                      name: 'Funk, Waters and Sawayn'
                      phone: 941-324-3259
                      email: leffler.ansley@example.net
                      birthday: 27/02/1994
                properties:
                  status:
                    type: integer
                    example: 1
                  error:
                    type: boolean
                    example: false
                  notebook:
                    type: array
                    example:
                      -
                        id: 1
                        fio: 'Dr. Godfrey Howell'
                        name: 'Funk, Waters and Sawayn'
                        phone: 941-324-3259
                        email: leffler.ansley@example.net
                        birthday: 27/02/1994
                    items:
                      type: object
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiV1NotebookId
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiV1NotebookId
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the notebook.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
